cartgc/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from cartgc.maindb import views
from django.contrib import auth
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import os

admin.autodiscover()

urlpatterns = patterns('cartgc.maindb',

    # Home
    url(r'^$', 'views.gethome', name='gethome'),

    # Statics files section
    url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/media/favicon.ico'}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATICFILES_DIRS}),

    # Admin section
    url(r'^admin/', include(admin.site.urls)),

    # Web-Admin contact
    url(r'^getcontact/$', 'views.getcontact'),

    # carteles
    url(r'^signs/$', 'views.cartel_viewall', name='cartel_viewall',kwargs={'view':"list"}),
    url(r'^signs/(?P<view>(list|icons))/$', 'views.cartel_viewall', name='cartel_viewall'),
    url(r'^sign/new/$', 'views.cartel_add', name='cartel_add'),
    url(r'^sign/delete/(?P<idc>\d+)/$', 'views.cartel_delete', name='cartel_delete'),
    url(r'^sign/view/(?P<idc>\d+)/$', 'views.cartel_view', name='cartel_view'),
    url(r'^sign/view/(?P<idc>\d+)/boxsign/$', 'views.boxsign', name="boxsign"),
    url(r'^sign/view/(?P<idc>\d+)/listsign/$', 'views.listsign', name="listsign"),
    url(r'^sign/view/(?P<idc>\d+)/lastact/$', 'views.xCartel_lastact', name="xCartel_lastact"),
    url(r'^sign/view/(?P<idc>\d+)/statusbox/$', 'views.xCartel_statusbox', name="xCartel_statusbox"),
    url(r'^sign/view/(?P<idc>\d+)/lastip/$', 'views.xCartel_lastip', name="xCartel_lastip"),
    url(r'^sign/edit/(?P<idc>\d+)/$', 'views.cartel_edit', name='cartel_edit'),
    url(r'^sign/edit/(?P<idc>\d+)/deletetask/(?P<idt>\d+)/$', 'views.cartel_edit_deltask', name='cartel_edit_deltask'),
    url(r'^sign/edit/(?P<idc>\d+)/deletetasks/$', 'views.cartel_edit_deltasks', name='cartel_edit_deltasks'),
    url(r'^sign/edit/(?P<idc>\d+)/addtask/(?P<taskchrs>[a-z|0-9]+)/$', 'views.cartel_edit_addtask', name='cartel_edit_addtask'),

    # Tasks
    url(r'^tasks/$', 'views.tasks', name='tasks'),
    url(r'^tasks/del/(?P<typedel>(all|inc|prg))/$', 'views.carteles_deltasks', name='carteles_deltasks'),

    # mensajes
    url(r'^messages/$','views.mensaje_viewall', name='mensajes_viewall'),
    url(r'^message/edit/(?P<idm>\d+)/$', 'views.mensaje_edit', name='mensaje_edit'),
    url(r'^message/new/$', 'views.mensaje_new', name='mensaje_new'),
    url(r'^message/delete/(?P<idm>\d+)/$', 'views.mensaje_del', name='mensaje_del'),

    # Paquete de mensajes
    url(r'^messages/packages/$','views.packages_viewall', name='packages_viewall'),
    url(r'^messages/package/new/$','views.package_new', name='package_new'),
    url(r'^messages/package/edit/(?P<idp>\d+)/$','views.package_edit', name='package_edit'),
    url(r'^messages/package/delete/(?P<idp>\d+)/$','views.package_delete', name='package_delete'),

    # Historiales
    url(r'^log/(?P<dyear>\d{4})/(?P<dmonth>\d{2})/(?P<dday>\d{2})(?:/(?P<dsign>\d+))?/$', 'views.logdatesign', name='logdatesign'),

    # Config Web
    url(r'^config/$','views.config_web', name='config_web'),

    # Log In
    url(r'^login/$','views.login', name='login'),
    url(r'^logout/$','views.logout', name='logout'),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),

)

cartgc/maindb/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines for those models you wish to give write DB access
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models
import datetime
import time

from cartgc.maindb.optcfg import *



def local_to_utc(t):
    secs = time.mktime(t)
    return time.gmtime(secs)

def utc_to_local(t):
    secs = calendar.timegm(t)
    return time.localtime(secs)


class AuthGroup(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(unique=True, max_length=80)
    class Meta:
        managed = False
        db_table = 'auth_group'

class AuthGroupPermissions(models.Model):
    id = models.IntegerField(primary_key=True)
    group_id = models.IntegerField()
    permission = models.ForeignKey('AuthPermission')
    class Meta:
        managed = False
        db_table = 'auth_group_permissions'

class AuthPermission(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    content_type_id = models.IntegerField()
    codename = models.CharField(max_length=100)
    class Meta:
        managed = False
        db_table = 'auth_permission'

class AuthUser(models.Model):
    id = models.IntegerField(primary_key=True)
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField()
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=75)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()
    class Meta:
        managed = False
        db_table = 'auth_user'

class AuthUserGroups(models.Model):
    id = models.IntegerField(primary_key=True)
    user_id = models.IntegerField()
    group = models.ForeignKey(AuthGroup)
    class Meta:
        managed = False
        db_table = 'auth_user_groups'

class AuthUserUserPermissions(models.Model):
    id = models.IntegerField(primary_key=True)
    user_id = models.IntegerField()
    permission = models.ForeignKey(AuthPermission)
    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'

class DjangoAdminLog(models.Model):
    id = models.IntegerField(primary_key=True)
    action_time = models.DateTimeField()
    user_id = models.IntegerField()
    content_type_id = models.IntegerField(blank=True, null=True)
    object_id = models.TextField(blank=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    class Meta:
        managed = False
        db_table = 'django_admin_log'

class DjangoContentType(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    class Meta:
        managed = False
        db_table = 'django_content_type'

class DjangoSession(models.Model):
    session_key = models.CharField(unique=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

class MaindbBrillo(models.Model):

    id = models.IntegerField(primary_key=True)
    percentbrightness = models.PositiveSmallIntegerField(db_column='percentBrightness') # Field name made lowercase.
    valuebrightness = models.PositiveSmallIntegerField(db_column='valueBrightness') # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'maindb_brillo'

    def __unicode__(self):
        return "%s %c" % (self.percentbrightness,chr(37))


class MaindbCartel(models.Model):

    id = models.IntegerField(primary_key=True)
    namecartel = models.CharField(db_column='nameCartel', max_length=50, blank=True) # Field name made lowercase.
    laststatus = models.IntegerField(db_column='lastStatus', blank=True, null=True) # Field name made lowercase.
    lasterrors = models.IntegerField(db_column='lastErrors', blank=True, null=True) # Field name made lowercase.
    lasttime = models.DateTimeField(db_column='lastTime', blank=True, null=True) # Field name made lowercase.
    lasttemp = models.IntegerField(db_column='lastTemp', blank=True, null=True) # Field name made lowercase.
    lastbrightness = models.ForeignKey(MaindbBrillo, db_column='lastBrightness_id', blank=True, null=True) # Field name made lowercase.
    lastmessages = models.CharField(db_column='lastMessages', max_length=300, blank=True) # Field name made lowercase.
    lastbroadcasting = models.CharField(db_column='lastBroadcasting', max_length=CHARSMAX, blank=True, null=True) # Field name made lowercase.
    lastip = models.CharField(db_column='lastIP', max_length=15, blank=True, null=True) # Field name made lowercase.
    lastlogin = models.DateTimeField(db_column='lastLogin', blank=True, null=True) # Field name made lowercase.
    lastreading = models.DateTimeField(db_column='lastReading', blank=True, null=True) # Field name made lowercase.
    taskstodo = models.TextField(db_column='tasksToDo', blank=True, null=True) # Field name made lowercase.
    historylog = models.TextField(db_column='historyLog', blank=True, null=True) # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'maindb_cartel'

    def cleanCartel(self):
        self.laststatus = None
        self.lasterrors = None
        self.lasttime = None
        self.lasttemp = None
        self.lastbrightness = None
        self.lastmessages = ""
        self.lastbroadcasting = None
        self.lastip = None
        self.lastlogin = None
        self.lastreading = None
        self.tasktodo = None
        self.historylog = None
        self.save()

    def getDefStatus(self):
        defStatus = {'bit7': STATUS07,
                     'bit6': STATUS06,
                     'bit5': STATUS05,
                     'bit4': STATUS04,
                     'bit3': STATUS03,
                     'bit2': STATUS02,
                     'bit1': STATUS01,
                     'bit0': STATUS00,
                    }
        return defStatus

    def getDefErrors(self):
        defErrors = {'bit7': ERRORS07,
                     'bit6': ERRORS06,
                     'bit5': ERRORS05,
                     'bit4': ERRORS04,
                     'bit3': ERRORS03,
                     'bit2': ERRORS02,
                     'bit1': ERRORS01,
                     'bit0': ERRORS00,
                    }
        return defErrors

    def getStatusCartel(self):
        statebits = {'bit7': False, 'bit6': False, 'bit5': False, 'bit4': False, 'bit3': False, 'bit2': False, 'bit1': False, 'bit0': False}
        if self.laststatus is not None:
          for i in range(0,8):
            statebits["bit"+str(i)] = self.laststatus & (2**i) != 0
        return statebits

    def getErrorsCartel(self):
        errorsbits = {'bit7': False, 'bit6': False, 'bit5': False, 'bit4': False, 'bit3': False, 'bit2': False, 'bit1': False, 'bit0': False}
        if self.lasterrors is not None:
            for i in range(0,8):
                errorsbits["bit"+str(i)] = self.lasterrors & (2**i) != 0
        return errorsbits

    def getElapsedTimeFrom(self,src_datetime,typeret="arr",blacklist="",shortxt=True):

        diff_datetime = {strhours: 0, strminutes: 0, strseconds: 0}

        if src_datetime:
          time_srcdt = time.mktime(src_datetime.timetuple())
          time_datetimenow = time.mktime(time.gmtime())
          diff_datetimes = time_datetimenow - time_srcdt

          diff_hours = int(diff_datetimes / TIME_HOURSECS)
          diff_minutes = int(diff_datetimes / TIME_MINSECS) % TIME_MINSECS
          diff_seconds = int(diff_datetimes) % TIME_MINSECS

          if typeret=="arr":

            diff_datetime = {strhours: diff_hours, strminutes: diff_minutes, strseconds: diff_seconds}
            return diff_datetime

          else:

            if shortxt==True:
              strhours = "h"
              strminutes = "m"
              strseconds = "s"
            else:
              strhours = "horas"
              strminutes = "minutos"
              strseconds = "segundos"

            str_part_h = ["","%d%s" % (diff_hours, strhours)][("h" in blacklist) == False]
            str_part_m = ["","%d%s" % (diff_minutes, strminutes)][("m" in blacklist) == False]
            str_part_s = ["","%d%s" % (diff_seconds, strseconds)][("s" in blacklist) == False]

            str_dtret = ""

            if str_part_h:
              str_dtret = str_part_h
            if str_part_m:
              str_dtret = [str_dtret + " " + str_part_m,str_part_m][str_dtret == ""]
            if str_part_s:
              str_dtret = [str_dtret + " " + str_part_s,str_part_s][str_dtret == ""]

            return str_dtret


    def getElapsedTimeFromLastLogin(self):
        diff_datetime = {'h': 0, 'm': 0, 's': 0}
        if self.lastlogin is not None:
            time_lastlogin = time.mktime(self.lastlogin.timetuple())
            time_datetimenow = time.mktime(time.gmtime())
            diff_datetimes = time_datetimenow - time_lastlogin

            diff_hours = int(diff_datetimes / TIME_HOURSECS)
            diff_minutes = int(diff_datetimes / TIME_MINSECS) % TIME_MINSECS
            diff_seconds = int(diff_datetimes) % TIME_MINSECS

            diff_datetime = {'h': diff_hours, 'm': diff_minutes, 's': diff_seconds}
        return diff_datetime

templates/cartel/add.html
{% extends "base.html" %}

{% block title %} Cartel nuevo {% endblock %}

{% block content %}

{% load static %}
{% load tz %}
{% static "information.png" as informationimg %}
{% static "warning.png" as warningimg %}

    <div class="headerlinks">
        <div class="divheaderlinks">
            <h1 class="header"><a href="/" />Inicio</a> > <a href="/signs/" />Carteles</a> > Nuevo Cartel </h1>
        </div>
    </div>

    <form action="." method="POST">
    {% csrf_token %}
        <table style="margin-top: 30px; margin-left: 30px; width: 700px;">
            <tr><td colspan="2" class="title" style="border-bottom: 1px #ccc solid;">&raquo; Nuevo cartel &laquo;</td></tr>
            <tr>
                <td class="label">
                    Nro. Cartel
                </td>
                <td class="dataright" style="border-right: 1px #ccc solid;">{{ form.id }}
                    <span style="font-size: 10pt; color: #e44;">
                    Valores que no puede elegir:
                    {% for xNOID in noIDSAvaible %}
                        {{ xNOID }}{% ifnotequal forloop.last True %},{% endifnotequal %}
                    {% endfor %}
                    </span>
                </td>
            </tr>
            <tr>
                <td class="label">
                    Ubicaci&oacute;n/Nombre
                </td>
                <td class="dataright" style="border-right: 1px #ccc solid;">
                    {{ form.namecartel }} {% if form.nameCartel.errors %}<br />{{ form.namecartel.errors }}{% endif %}
                </td>
            </tr>
            <tr>
              <td colspan="2" colspan="2" style="text-align: center; width: 100%;" class="label">
                <div style="text-align: center; margin-top: 10px; padding: 10px;">
                  <button id="submitmessage" type="submit" class="button ion-checkmark-round" style="font-size: 12pt; border: 1px #aaa solid; border-radius: 5px; color: #333;"> Crear cartel</button>
                </div>

              </td>
            </tr>
        </table>

    </form>

{% endblock %}

templates/cartel/edit.html
{% extends "base.html" %}
{% load static %}

{% block title %} Editando cartel {% endblock %}

{% block content %}
{% static "information.png" as informationimg %}
{% static "warning.png" as warningimg %}
{% static "save.png" as savebutton %}
{% static "arrow_down.png" as item_movedown %}
{% static "arrow_up.png" as item_moveup %}
{% static "nored.png" as item_delete %}
{% static "arrow_left.png" as item_add %}
    <div class="headerlinks">
        <div class="divheaderlinks">
            <h1 class="header"><a href="/" />Inicio</a> > <a href="/signs/" />Carteles</a> > {{ xCartel.namecartel| truncatechars:32 }}</h1>
        </div>
    </div>
    <form id="editcartel" action="." method="POST">
    {% csrf_token %}
    {{ form.management_form }}
    {{ form_errors }}
    {{ form.id.as_hidden }}
        <table style="margin-top: 30px; margin-left: 30px; width: 700px;box-shadow: 0 0 5px 3px #ccc;">

            <tr style="text-align: center;">
                <td class="title" style="border: none; padding-bottom: 20px;padding-top: 20px; background-color: rgba(180,180,180,0.5); border:0px #ccc solid;border-bottom:1px #ccc solid;;" colspan="2">
                    <span id="title_namecartel" style="font-variant:small-caps; font-size: 16pt;font-weight: bold; margin-bottom: 10px;">
                        {{ xCartel.namecartel }}
                    </span>
                </td>
            </tr>

            <tr>
                <td class="label" width="200">
                    Nombre
                </td>
                <td class="dataright" style="border-right: 1px #ccc solid;">
                    {{ form.namecartel }} {% if form.nameCartel.errors %}<br />{{ form.namecartel.errors }}{% endif %}
                </td>
            </tr>
            {% ifequal showBrightness True %}
            <tr>
                <td class="label">
                    <img src="{{ informationimg }}" width="24" height="24" align="left" />Brillo<br /><span class="aclaracion"> # Solo version C</span>
                </td>
                <td class="dataright" style="border-right: 1px #ccc solid;">
                    {{ form.lastbrightness }}{% if form.lastbrightness.errors %}<br />{{ form.lastbrightness.errors }}{% endif %}
                </td>
              </tr>
            {% endifequal %}
            {% ifequal Messages_available True %}
            <tr>
                <td class="label">
                    Mensajes
                </td>
                <td class="dataright" style="border-right: 1px #ccc solid;text-align: center; height: 350px;">


                  <div style="width:100%;">
                        <div id="msgcont" style="width: 100%; margin: 0 auto; padding-bottom:200px;">
                            <div id="msgcont_mymsg" style="width: 49%; height: 200px; float: left; margin: auto;">
                                <span style="font-size: 8pt; text-decoration: underline; color: #666; text-align: center;">
                                    &Uacute;ltimos mensajes del cartel actual:
                                </span>
                                <select id="mymensajes" multiple="multiple" name="mymensajes[]" style="color: #aaa;font-size: 8pt;height: 200px;width: 100%;" />
                                {% if xCartel.getMssgOBJ %}
                                    {% for xMensaje in xCartel.getMssgOBJ %}
                                    <option value="{{ xMensaje.idmessage }}">
                                        {{ xMensaje.contentmessage }}
                                    </option>
                                    {% endfor %}
                                {% endif %}
                                </select>
                                <div id="mymensajes_action" style="display:none;">
                                    <a href="javascript:;" style="color:grey;" id="mymjs_itemup"/>
                                        <img src="{{ item_moveup }}" width="16" height="16" align="left"/>
                                    </a>
                                    <a href="javascript:;" style="color:white;" id="mymjs_itemdown"/>
                                        <img src="{{ item_movedown }}" width="16" height="16" align="left"/>
                                    </a>
                                    <a href="javascript:;" style="color:white; padding:0px; margin: 0px;" id="mymjs_itemdelete"/>
                                        <img src="{{ item_delete }}" width="16" height="16" align="right"/>
                                    </a>
                                </div>
                            </div>

                            <span style="font-size: 8pt; text-decoration: underline; color: #666; text-align: center;">
                                Todos los mensajes:
                            </span>

                            <div id="msgcont_allmsg" style="width: 49%; height: 200px; float:right; ">
                                <select id="allmensajes" multiple="multiple" name="allmensajes[]" style="color: #aaa;font-size: 8pt;height: 200px;width: 100%;" />
                                {% if allMensajes %}
                                    {% for xMensaje in allMensajes %}
                                    <option value="{{ xMensaje.idmessage }}">
                                       {{ xMensaje.contentmessage }}
                                    </option>
                                    {% endfor %}
                                {% endif %}
                                </select>
                                <div id="allmensajes_action" style="display:none;">
                                    <a href="javascript:;" style="padding:0px; margin: 0px;" id="addtocartel"/>
                                        <img src="{{ item_add }}" width="16" height="16" align="left" />
                                    </a>
                                </div>
                            </div>
                        </div>
                        <span id="msgcontent" style="border: 1px #aaa dashed; background-color: #eee; float:left; padding: 5px; margin-top: 25px; width: 98%; text-align:left; font-size: 8pt;line-height:200%;color: #333;display:none;">
                          <u><b>Contenido</b></u><br><span id="msgcontent_content" style="margin-left: 20px;color:#999; font-style:italic; font-size: 11pt;"></span><br />
                          <u><b>Configuraci&oacute;n</b></u><br><span id="msgcontent_config" style="margin-left: 20px; color: #999; font-style:italic; font-size: 11pt;"></span><br />
                        </span>
                    <div style="display:none;">
                    {{ form.lastmessages }}
                    </div>
                    <div style="bottom:0px;text-align:left;">
                      <div style="width: 100%; text-align:center; margin-top: 20px;">
                        <span style="font-size: 11pt; color: #666; font-weight: bold; text-align:center; ">Paquetes de Mensajes</span><br />
                      </div>
                      {% for idPackage, dictPackage in strAllPackages.items %}

                        {% for xPckg in allPackages %}

                          {% ifequal xPckg.id idPackage %}
                          <label id="pckg{{ idPackage }}"><input type="radio" name="pckg" value="{{ idPackage }}"><span style="font-weight: bold; text-decoration:underline; margin-left: 5px;">{{ xPckg.namepackage }}</span></label><br />
                          {% endifequal %}

                          {% endfor %}

                        {% for idMssg, valueMssg in dictPackage.items %}
                         <p style="margin-left: 10px; font-size: 8pt; color: #aaa; line-height:80%;">{{ forloop.counter }}) {{ valueMssg|truncatechars:80 }}</p>
                        {% endfor%}

                      {% endfor %}
                    </div>
                </td>
            </tr>
            {% endifequal %}
            <tr>
                <td colspan="2" style="text-align: center; width: 100%;" class="label">
                    <div style="margin-left: 5px; padding: 3px; line-height: 100%; width: 97%; font-size: 10pt; align:right; text-align: justify; text-indent: 20px; font-weight: normal;">
                      <img src="{{ warningimg }}" width="32" height="32" align="left" style="margin: 10px;"/>
                      <p style="margin-left: 60px;">
                      Los cambios realizados <b>relacionados con la visualizaci&oacute;n del cartel</b> tendr&aacute;n efecto cuando el cartel <b>complete la respectiva tarea</b>.
                      </p>
                    </div>
                    <div style="text-align: center; margin-top: 10px; padding: 10px;">
                      <button id="submitform" type="submit" class="button ion-checkmark-round" style="font-size: 12pt; border: 1px #aaa solid; border-radius: 5px; color: #333;"> Guardar cambios</button><br /><br />
                    </div>
                  </td>
            </tr>
        </table>
    </form>
    <div style="text-align: left; margin-top: 10px; padding: 10px;">
      <a href="/sign/view/{{ xCartel.id }}/"/><i class="icon ion-android-arrow-back"></i><span style="margin-left: 10px;">Volver a <b>{{ xCartel.namecartel }}</b></span></a>
    </div>
    <div style="text-align: left; margin-top: 10px; padding: 10px;">
        <a href="/signs/"/><i class="icon ion-navicon-round"></i><span style="margin-left: 10px;">Volver a todos los Carteles</span></a>
    </div>
    <br /><br />
<script>

    $(document).ready(function(){

      {% ifequal Messages_available True %}
        var timeRefresh=1000;
        var allMjs = {};
        var allCfgs = {}
        var allPckgs = {};
        var lastMSG = 0;

        {% for xMessage in allMensajes %}
        allMjs[ {{ xMessage.idmessage }} ] = "{{ xMessage.contentmessage }}";
        allCfgs[ {{ xMessage.idmessage }} ] = "{{ xMessage.getSTRConfig }}" ;
        {% endfor %}

        {% for xPackage in allPackages %}
        allPckgs[ {{ xPackage.id }} ] = "{{ xPackage.messages }}";
        {% endfor %}

        $('#id_namecartel').keyup(function (){
          $("#title_namecartel").text($("#id_namecartel").val());
        });

        $('#mymensajes').change(function () {
            $("#mymensajes_action").show();
        });

        $('#mymensajes').click(function () {
            show_infosign(this.value);
        });

        function updatemjs(mjs){
            $("#id_lastmessages").text(mjs);
        }

        function setPackage(mjs){
          $("#id_lastmessages").text(mjs);
        }

        // Click on Package
        {% for xPackage in allPackages %}
        $('#pckg{{ xPackage.id }}').click(function (event) {
          $('#mymensajes').empty();
          mssgsvals = allPckgs[ {{xPackage.id}} ].split(',');
          $.each( mssgsvals, function( k, v ) {
            $("#mymensajes").append('<option value="'+v+'">' + allMjs[ v ] + '</option>');
          });

          setPackage("{{ xPackage.messages }}");
          });
        {% endfor %}

        // Show info sign in section
            function show_infosign(id){
                $("#msgcontent").show();
                $("#msgcontent_content").text('“ '+allMjs[ id ]+' ”');
                $("#msgcontent_config").text(allCfgs[ id ]);
            }

        // botones allmensajes
            // itemup
            $('#mymjs_itemup').click(function (event) {
                var $selectedvals = $('#mymensajes option:selected')
                if($selectedvals.length){
                    $selectedvals.first().prev().before($selectedvals);
                }
                var values = $.map($('#mymensajes option'), function(e) { return e.value; });
                values.join(',');
                updatemjs(values);
            });

            // itemdown
            $('#mymjs_itemdown').click(function (event) {
                var $selectedvals = $('#mymensajes option:selected')
                if($selectedvals.length){
                    $selectedvals.last().next().after($selectedvals);
                }
                var values = $.map($('#mymensajes option'), function(e) { return e.value; });
                values.join(',');
                updatemjs(values);
            });

            // itemdelete
            $('#mymjs_itemdelete').click(function (event) {
                var selectedvals = $("#mymensajes").val();
                $.each( selectedvals, function( k, v ) {
                    $("#mymensajes option:selected").remove();
                });
                $("#mymensajes option:selected").removeAttr("selected");
                $("#mymensajes_action").hide();
                var values = $.map($('#mymensajes option'), function(e) { return e.value; });
                values.join(',');
                updatemjs(values);
            });

        // lista allmensajes
            // mostrar
            $('#allmensajes').click(function (event) {
                $("#allmensajes_action").show();
            });

            $('#allmensajes').click(function () {
                show_infosign(this.value);
            });

            // botones allmensajes
            $('#addtocartel').click(function (event) {
                var selectedvals = $("#allmensajes").val();
                $.each( selectedvals, function( k, v ) {
                    $("#mymensajes").append('<option value="'+v+'">' + allMjs[ v ] + '</option>');
                });
                var values = $.map($('#mymensajes option'), function(e) { return e.value; });
                values.join(',');
                updatemjs(values);
            });

            //add double
            $('#allmensajes').dblclick(function (event) {
                $('#addtocartel').click();
            });
        {% endifequal %}
    });

</script>

{% endblock %}

templates/cartel/lastip.html
{% ifnotequal xCartel.lastip None %}{{ xCartel.lastip }}{% else %}<span style="color: #ccc;font-size:10pt;font-style: italic;">Ninguna.</span>{% endifnotequal %}